name: shuttle_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_bottom_navigation_bar: ^0.3.2
  google_maps_controller: ^1.2.0
  google_directions_api: ^0.9.0
  flutter_form_builder: ^6.0.1
  google_maps_flutter: ^2.0.6
  permission_handler: ^8.1.2
  splash_screen_view: ^3.0.0
  cloud_firestore: ^2.3.0
  cupertino_icons: ^1.0.2
  flutter_spinkit:
  introduction_screen:
  geoflutterfire: ^3.0.1
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  flutter_bloc: ^7.0.1
  geolocator: ^7.2.0+1
  equatable: ^2.0.3
  location: ^4.3.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/onBoarding/
    - images/shuttles/


#  fonts:
#    - family: DancingScript
#      fonts:
#        - asset: fonts/dancing_script.ttf
#
